export const APP_STORE_ID = '6758858102';
export const APP_STORE_URL = 'https://apps.apple.com/us/app/snaglist/id6758858102';
export const APP_STORE_BADGE_URL = 'https://tools.applemediaservices.com/api/badges/download-on-the-app-store/black/en-us?size=250x83';
export const WEBSITE_URL = 'https://snaglist.app';
export const LOGO_PATH = '/Snaglist_Logo.jpeg';
export const APP_NAME = 'Snaglist';
export const APP_TAGLINE = 'The Snagging App Built by a Site Manager';
export const CTA_VALUE_PROPS = ['Create snag lists', 'Share with contractors', 'Track completions'];
export const CTA_HEADING = 'Managing your own projects?';
export const CTA_SUBHEADING = 'Join the waitlist';
export const POST_COMPLETION_CTA = 'Want to manage your own projects? Join the waitlist for early access';
export const EMPTY_STATE_CTA = 'No snags to review. Want to create your own snag lists? Join the waitlist';
